version: '3.8'
services:
  web:
    image: nginx:latest
    ports:
      - '9100:80'
    volumes:
      - ./src/backend:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
    depends_on:
      - php-fpm
      - redis

  php-fpm:
    image: php:8.2-fpm
    volumes:
      - ./src/backend:/var/www/html
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:latest
    ports:
      - '6377:6377'

  frontend:
    build: ./src/frontend
    ports:
      - '5173:5173'
    environment:
      - PORT=5173

