version: '3.8'
services:
  web:
    image: nginx:latest
    ports:
      - '9100:80'
    volumes:
      - ./src/backend:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  php-fpm:
    image: php:8.2-fpm
    volumes:
      - ./src/backend:/var/www/html

  redis:
    image: redis:latest

  frontend:
    build: ./src/frontend
    ports:
      - '5173:5173'
    environment:
      - PORT=5173

